[[manager.prepend_keymap]]
on   = [ "g", "t" ]
run  = "plugin recycle-bin -- open"
desc = "Go to Trash"

[[manager.prepend_keymap]]
on   = [ " ", "t" ]
run  = "plugin recycle-bin"
desc = "Trash Menu (Restore, Empty, etc.)"
